### ISSUE TITLE
Get bounding box from a list of x/y/z Spherical Mercator tiles

### ISSUE THREAD

**Issue by bertrandg** [veltman/xyz-affair#1]
Hi,
Any idea to do the opposite?
I have some folder trees and would like to know bounds available in these layers..
thanks

**Comment by veltman** [comment]
You can use the formulas here to go from tile number to lat/lng:

http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Implementations

**Comment by bertrandg** [comment]
Thanks!
